services:
  gui:
    build:
      context: .
      dockerfile: Dockerfile.gui
    volumes:
      - /dev/shm/:/dev/shm/
      - /tmp
    ports:
      - "8080:8080"
    restart: always
  gatorcat:
    image: ghcr.io/jeffective/gatorcat:0.4.7
    command: run --ifname enx00e04c68191a --plugin-zenoh-config-default --auto-scan-plugin-zenoh-enable --config-file /eni.zon
    volumes:
      - /dev/shm/:/dev/shm/
      - /tmp
      - ./eni.zon:/eni.zon:ro
    network_mode: host
    restart: always
  zenoh-router:
    image: eclipse/zenoh
    restart: always
    ports:
      - 7447:7447
      - 8000:8000
    volumes:
      - /dev/shm/:/dev/shm/
      - /tmp
    environment:
      - RUST_LOG=debug

# networks:
#   ethercat:
#     driver: macvlan
#     driver_opts:
#       macvlan_mode: passthru
#       parent: enx00e04c68191a