[project]
name = "python-gui"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cbor2>=5.7.0",
    "eclipse-zenoh>=1.5.1",
    "nicegui>=3.0.3",
]
