name: Tests

on:
  push:

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Zig Compiler
        uses: mlugg/setup-zig@v1.2.1
        with:
          version: 0.14.0

      - name: Build and test Zig Project
        run: zig build ci-test
      
      - name: Archive zig-out
        uses: actions/upload-artifact@v4
        with:
          name: Release-safe binaries
          path: |
            zig-out/x86_64-linux-musl/
            zig-out/aarch64-linux-musl/
            zig-out/x86_64-windows-gnu/
        


